#!/bin/bash

su odoo -c "psql raktar -c \"
INSERT INTO legrand_anyaghiany_log (create_date, datum, cikk_id, szefo_keszlet, mterv_igeny, gyartas_igeny, mterv_gyartas_elter, gyartas_elter)
  SELECT now(), now(), cikk_id, szefo_keszlet, mterv_igeny, gyartas_igeny, mterv_gyartas_elter, gyartas_elter
  FROM legrand_anyaghiany
  WHERE mterv_gyartas_elter < 0
  ORDER BY cikk_id
\"
"

su odoo -c "psql raktar -c \"
INSERT INTO legrand_gyartasi_lap_log (datum, create_uid, create_date, write_uid, write_date, gyartasi_lap_id, state, gyartasi_hely_id, rendelesszam, termekkod, hatarido,
                                      hatralek_db, rendelt_ora, teljesitett_ora, hatralek_ora, szamlazott_ora, szamlazhato_ora, termekcsoport, leallas_ok, aktivitas, leallas_felelos)
  SELECT now(), create_uid, create_date, write_uid, write_date, id, state, gyartasi_hely_id, rendelesszam, termekkod, hatarido,
    hatralek_db, rendelt_ora, teljesitett_ora, hatralek_ora, szamlazott_ora, szamlazhato_ora, termekcsoport, leallas_ok, aktivitas, leallas_felelos
  FROM legrand_gyartasi_lap
  WHERE state IN ('mterv', 'gyartas') AND active
  ORDER BY id
\"
"
